# This file may be removed if the fits of Rails cops are preferred instead.

inherit_from: ./general.yml

AllCops:
  Exclude:
  - 'bin/**/*'
  - 'config/**/*.json'
  - 'db/**/*'
  - 'test/dummy/**/*'
  - 'vendor/**/*'
Layout/LineLength:
  Exclude:
  - 'config/**/*'
